version: "3.8"

services:
  database:
    container_name: mysql-db
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=crypto_market
      - MYSQL_USER=csongor
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=pass123
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 15

  server:
    container_name: laravel-api
    image: laravel-api-prod:1.0.0
    build:
      dockerfile: Dockerfile
      context: ./server
      target: php
      args:
        - APP_ENV=local
    working_dir: /var/www
    volumes:
      - "./server:/var/www"
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  client:
    container_name: flutter-ui
    image: flutter-ui-prod:1.0.0
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - "./client:/home/developer"
    depends_on:
      - server

volumes:
  db-data: ~
